data:
  dataset: ukb
  batch_size: 32
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 128
  image_folder: imagenet_full_size/061417/
  num_workers: 0
  pin_mem: true
  root_path: /dss/dssmcmlfs01/pr62la/pr62la-dss-0002/MSc/Hui/UKB_CAT12
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  in_chans: 1
logging:
  folder: logs/vitb16-ukb-ep.1000/
  write_tag: jepa
  disable_wandb: false
mask:
  allow_overlap: false
  aspect_ratio:
  - 1.0
  - 1.0
  enc_mask_scale:
  - 0.54
  - 0.67
  min_keep: 1
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.015
  - 0.02
meta:
  proj_name: ijepa
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.0005
  start_lr: 0.0001
  warmup: 20
  weight_decay: 0.04
